@baseUrl = http://localhost:8000/api

### Criar filme manualmente
POST {{baseUrl}}/movies/
Content-Type: application/json

{
  "tmdb_id": 9003,
  "title": "Filme comendia",
  "release_date": "2011-10-15",
  "vote_average": 4.0,
  "popularity": 6.5,
  "overview": "Descrição de terror.",
  "is_custom": true
}

### Listar filmes
GET {{baseUrl}}/movies/

### Filtro por nota mínima
GET {{baseUrl}}/movies/?vote_average__gte=4

### Filtro por ano de lançamento
GET {{baseUrl}}/movies/?release_date__gte=2011-01-01&release_date__lte=2017-12-31

### Pesquisa por palavra-chave
GET {{baseUrl}}/movies/?search=sex

### Ordenar por popularidade decrescente
GET {{baseUrl}}/movies/?ordering=-popularity

### Browser
http://localhost:8000/api/movies/

http://localhost:9000/docs

http://localhost:15672/
(guest/guest)
### Relatório de filmes mais bem avaliados
GET http://localhost:9000/report/highest-rated-movies
### Resumo de popularidade dos filmes
GET http://localhost:9000/report/popular-movies-summary

### Debug - Verificar dados no MongoDB
GET http://localhost:9000/debug/movies