@baseUrl = http://localhost:8000/api

### Criar filme manualmente
POST {{baseUrl}}/movies/
Content-Type: application/json

{
  "tmdb_id": 9005,
  "title": "Filme Teste",
  "release_date": "2023-10-15",
  "vote_average": 3.0,
  "popularity": 999,
  "overview": "Descrição de teste.",
  "is_custom": true
}

### Listar filmes
GET {{baseUrl}}/movies/

### Filtro por nota mínima
GET {{baseUrl}}/movies/?vote_average__gte=3

### Filtro por ano de lançamento
GET {{baseUrl}}/movies/?release_date__gte=2000-01-01&release_date__lte=2025-12-31

### Pesquisa por palavra-chave
GET {{baseUrl}}/movies/?search=teste

### Ordenar por popularidade decrescente
GET {{baseUrl}}/movies/?ordering=-popularity
###
GET http://localhost:8000/api/movies/

### Browser URLs
Django
http://localhost:8000/api/movies/

###
FastAPI
http://localhost:9000/docs

###
RabbitMQ
http://localhost:15672 (usuário/senha: guest)